### ISSUE TITLE
set_page_and_extract_portion_from does not work with Enumerables

### ISSUE THREAD

**Issue by wongwf82** [basecamp/geared_pagination#7]
When sorting with custom method, it will return Enumerables:
`Job.all.sort {|a, b| a.distance_from(current_user).to_i <=> b.distance_from(current_user).to_i }`

So the following will throw an error:
`set_page_and_extract_portion_from Job.all.sort {|a, b| a.distance_from(current_user).to_i <=> b.distance_from(current_user).to_i }`

> NoMethodError: undefined method `limit' for #<Array:0x00007feb05f8dfe8>

**Comment by wongwf82** [comment]
Perhaps to support Enumerables, in addition to Portion.rb having the following:
`   def from(scope)
      scope.limit(limit).offset(offset)
    end`

It could have something like `scope.drop(offset).first(limit)`?

**Comment by dhh** [comment]
If you've already loaded the whole collection, then I don't think Geared Pagination actually adds that much value. This is chiefly about ensuring that you don't load the entire dataset into memory and take a long time to render the page. But feel free to explore what such an addition might look like in a PR or a related gem.
